// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LxWoopCx2t6qU-VMBLNG0TYKDkN8jZc',
    appId: '1:762536351500:web:d105692593a6d1bd5c5b29',
    messagingSenderId: '762536351500',
    projectId: 'cra-complaint',
    authDomain: 'cra-complaint.firebaseapp.com',
    storageBucket: 'cra-complaint.appspot.com',
    measurementId: 'G-106151XESH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhS93rbgIouRnppIH2VXmB898N8F7VkUI',
    appId: '1:762536351500:android:a8fc8babc8eedb695c5b29',
    messagingSenderId: '762536351500',
    projectId: 'cra-complaint',
    storageBucket: 'cra-complaint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Tk_Aozn8Ez762fe3O00zD7nO5iXhd7s',
    appId: '1:762536351500:ios:be3627a4ea46ecbb5c5b29',
    messagingSenderId: '762536351500',
    projectId: 'cra-complaint',
    storageBucket: 'cra-complaint.appspot.com',
    iosClientId: '762536351500-64lr39bcsf6fu76agekfvsuosgh3co68.apps.googleusercontent.com',
    iosBundleId: 'com.example.craComplaints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Tk_Aozn8Ez762fe3O00zD7nO5iXhd7s',
    appId: '1:762536351500:ios:be3627a4ea46ecbb5c5b29',
    messagingSenderId: '762536351500',
    projectId: 'cra-complaint',
    storageBucket: 'cra-complaint.appspot.com',
    iosClientId: '762536351500-64lr39bcsf6fu76agekfvsuosgh3co68.apps.googleusercontent.com',
    iosBundleId: 'com.example.craComplaints',
  );
}
